### ISSUE TITLE
Twitter: Review API, capture most important fields

### ISSUE THREAD

**Issue by bstarling** [Data4Democracy/collect-social#5]
### Goal: 
Come up with a standard list of [tweet fields](https://dev.twitter.com/overview/api/tweets) to save (if available) . This is meant to be the "default" config list. The plan is to allow saving of full tweet object or a targeted list of fields but we want to come up with the most relevant fields that would be used by useful in nearly every project.

So far people have mentioned `coordinates` and `entities` (contains hashtags, user_mentions, urls) as potentially useful fields that are not currently captured by discursive.

### Additional info:
* Fields currently captured in a [discursive](https://github.com/Data4Democracy/discursive/blob/master/tweet_model.py).

**Comment by georgerichardson** [comment]
How about putting this to a poll in one of the channels populated by the intended analysts?

**Comment by georgerichardson** [comment]
Actually, maybe that's not such a good idea. There's a lot of fields to vote on!

**Comment by ccarey** [comment]
Well, I wish I had seen this post earlier! My fault for not actually reading the issues :) 

Right now I've implemented the following in the code:
```
	'id_str': twitter_post.id_str,
        'user_id': twitter_post.user.id_str,
        'text': twitter_post.text,
        'created_at': twitter_post.created_at,
        'retweet_count': twitter_post.retweet_count,
        'favorite_count': twitter_post.favorite_count,
```

Since get_posts takes in a user_id, and the only way thus far to get a user_id is to run get_user, my assumption was that as long as we had that user_id stored in the tweet database, we could run a join on the user and tweet databases to get the author-specific info for individual tweets.

In terms of other potentially useful tweet-specific information (as has been mentioned already):
- 'coordinates': twitter_post.coordinates.coordinates
- 'hashtags': twitter_post.entities.hashtags
- 'urls': twitter_post.entities.urls
- 'mentions': twitter_post.entities.mentions

"Mentions" might be especially useful to have in order to link up networks of users in the future.
